### ISSUE TITLE
standard_init_linux.go:228: exec user process caused: exec format error

### ISSUE THREAD

**Issue by dannyvfilms** [kiranshila/Doplarr#62]
Device: Raspberry Pi 4
OS: PiOS 11

Using Portainer, I added all fields shown in the guide (see attached image)

<img width="737" alt="Screen Shot 2022-02-26 at 8 43 50 AM" src="https://user-images.githubusercontent.com/44555970/155847233-bb02839c-f246-45c9-a27e-e4fdfdd219ec.png">

Upon running, I received one error constantly:
standard_init_linux.go:228: exec user process caused: exec format error

I'm not technically savvy, but does this error mean Doplarr is not compatible with ARM, or is it a different issue?

**Comment by kiranshila** [comment]
Yeah that looks like an architecture problem. Dopplar itself has no problems with ARM because it runs on the JVM, the docker container needs to have a matching kernel, though. The one I provide is only x86, but I believe the other container providers, hotio and lsio both have ARM versions. You could also just run the jar directly.

**Comment by dannyvfilms** [comment]
Since I haven’t studied the directions for running directly and am a bit more familiar with Docker, I’ll give the hotio container a try. Thanks for confirming my suspicion!

**Comment by kiranshila** [comment]
Closing for now - I'll make a note in the docs that the container we provide is x86 only
